logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8080"

[api]
entrypoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = true
